### ISSUE TITLE
that's not an issue

### ISSUE THREAD

**Issue by T4P4N** [N-O-D-E/N-O-D-E.net#13]
Can you tell me the name of the font used in your website please.

**Comment by oholiab** [comment]
https://fonts.google.com/specimen/Share+Tech+Mono

Found by going to https://n-o-d-e.net/, viewing page source and looking inside the head tag where there's the element:

```html
 <link href='https://fonts.googleapis.com/css?family=Share+Tech+Mono' rel='stylesheet' type='text/css'>
```

**Comment by T4P4N** [comment]
Thank You Very Much ! 👍

**Comment by T4P4N** [comment]
👍
